// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSal7abba8_g1hgR1su5KOsi2V979q2-M',
    appId: '1:381153283504:web:9d4fe62e16410dbf7b1a75',
    messagingSenderId: '381153283504',
    projectId: 'hallhelp-c1118',
    authDomain: 'hallhelp-c1118.firebaseapp.com',
    databaseURL: 'https://hallhelp-c1118-default-rtdb.firebaseio.com',
    storageBucket: 'hallhelp-c1118.appspot.com',
    measurementId: 'G-9FJ7HXMPNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaqJSWvE4xpMQyiv8fAer6gwi5axz79pM',
    appId: '1:381153283504:android:d98780119be9c7107b1a75',
    messagingSenderId: '381153283504',
    projectId: 'hallhelp-c1118',
    databaseURL: 'https://hallhelp-c1118-default-rtdb.firebaseio.com',
    storageBucket: 'hallhelp-c1118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHGQi_vYPRE2RfpNwaQSS4qBrSNF8kj0k',
    appId: '1:381153283504:ios:08b297e3285b82a27b1a75',
    messagingSenderId: '381153283504',
    projectId: 'hallhelp-c1118',
    databaseURL: 'https://hallhelp-c1118-default-rtdb.firebaseio.com',
    storageBucket: 'hallhelp-c1118.appspot.com',
    iosBundleId: 'com.example.hallhelp3',
  );

}